language: ruby
rvm:
  - 2.5.1
branches:
  except:
    - "/^v[0-9]+\\.[0-9]+\\.[0-9]+(?:-.*)?/"
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rubocop
  - bundle exec rspec
